### ISSUE TITLE
Ci Portal 구축을 위한 TO-DO 항목정리

### ISSUE THREAD

**Issue by kdkim2000** [kdkim2000/Vue.js3#1]
# 1. GitHub Enterprise Project 관리 주요기능

- Projects: Kanban 보드로 작업 관리를 시각화.
- Issues: 작업, 버그, 피드백 추적.
- Pull Requests (PRs): 코드 리뷰와 협업.
- Actions: CI/CD 파이프라인을 자동화.
- Advanced Security: 비밀 스캔, 코드 스캔 등을 통한 보안 강화.

# 2. GitHub Enterprise에 맞춘 협업 및 관리 전략
## 2.1 프로젝트 관리 (GitHub Projects)
GitHub Enterprise에서는 Projects를 확장하여 팀 간 협업을 용이하게 합니다.

- 설정 방법:
Project 생성: Admin 계정으로 접속 후 조직 또는 리포지토리에서 Projects 활성화.
- 컬럼 및 워크플로:
Backlog → To-Do → In Progress → Review → Done.
GitHub Actions를 이용해 이슈나 PR의 상태 변경 시 자동으로 컬럼 이동.

특화된 설정:
- 팀별 보드: 프론트엔드와 백엔드 팀별로 개별 보드를 생성.
- 권한 설정: 팀 구성원에게 적절한 읽기/쓰기 권한을 부여.
- 
## 2.2 Issues 활용
GitHub Enterprise의 Issues는 사용자 정의 템플릿, 네이밍 룰, 워크플로 자동화가 가능합니다.

- Issue 네이밍 규칙
[Frontend], [Backend], [Infra] 등의 태그를 추가.
예시:
[Frontend] Implement Login UI
[Backend] Create Authentication API
[Infra] Set up GitHub Actions Workflow
Issue 템플릿
템플릿을 통해 일관성을 유지:

```
name: Feature Request
about: "새로운 기능 요청"
title: "[FR] "
labels: enhancement
assignees: ''
```

### 기능 설명
어떤 기능이 필요한지 명확히 기술합니다.

### 완료 기준
- [ ] 작업 완료 시 확인 가능한 구체적인 조건 작성.

### 참고 자료
- 자동화:
- Issue 상태 변경: project automation 기능을 사용해 상태 변경을 자동화.
- Assignee 지정: GitHub Actions를 사용해 특정 조건에 따라 담당자를 자동 할당.

## 2.3 Pull Requests (PRs)와 코드 리뷰
PR과 코드 리뷰 프로세스는 팀 협업의 핵심입니다.

PR 템플릿
일관성을 위해 PR 템플릿 작성:

### 작업 내용
어떤 변경이 이루어졌는지 설명.

### 테스트
- [ ] 로컬 테스트 완료.
- [ ] CI/CD 통과 확인.

### 참고 자료
관련 이슈: #123
PR 리뷰 프로세스
승인 정책: 코드 병합 전에 최소 2명의 리뷰어 승인이 필요.
자동 병합: 모든 체크 통과 시 병합되도록 설정.

## 2.4 GitHub Actions로 CI/CD 설정
GitHub Actions는 GitHub Enterprise에서도 사용 가능합니다.

기본 Workflow 예제:
프론트엔드 및 백엔드 빌드를 위한 CI/CD 설정:

name: CI/CD Pipeline
```
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Run tests
        run: npm run test
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Spring Boot app
        run: ./mvnw clean package
        working-directory: backend
```
# 3. 통합 관리 및 권한 설정
GitHub Enterprise Server는 고급 권한 설정을 제공합니다.

## 3.1 팀 및 권한 관리
팀 구성: 프론트엔드, 백엔드, 인프라 팀별로 그룹화.
권한 레벨:
- Admin: 리포지토리 관리자.
- Write: 코드 기여자.
- Read: 읽기 전용 사용자.

## 3.2 비밀 관리 (Secrets)
- Settings > Secrets에서 CI/CD에 필요한 API 키, 인증 정보 등을 안전하게 저장.

# 4. 모범 사례
- 명확한 네이밍 규칙:

- 이슈, PR, 브랜치 이름을 일관되게 관리.
브랜치 네이밍 예: feature/login-ui, bugfix/api-error.
자동화:

- PR 병합 조건: 모든 CI 체크 통과 및 리뷰 승인 필요.
Kanban 이동: Actions로 상태 변경 자동화.
지속적인 피드백:

매주 또는 매달 Projects와 Issues를 검토하여 진행 상황 점검.

## 1. SCIM 지원 (공개 베타)
SCIM(System for Cross-domain Identity Management)은 사용자 수명 주기 관리를 위한 표준입니다. 3.14 버전에서는 SCIM 지원이 도입되어, 엔터프라이즈 관리자가 SCIM API를 통해 사용자 계정과 그룹을 자동으로 프로비저닝할 수 있습니다. citeturn0search12

활용 방안:

자동 사용자 관리: SCIM을 통해 새로운 사용자의 생성, 업데이트, 삭제를 자동화하여 관리 효율성을 높일 수 있습니다.
통합 인증 시스템 연동: 기존의 ID 관리 시스템과 연동하여 사용자 관리를 중앙집중화할 수 있습니다.

## 2. 보안 기능 강화
3.14 버전에서는 보안 관련 기능이 강화되었습니다. 예를 들어, 비밀 스캔 및 코드 스캔 기능이 개선되어 코드베이스 내의 민감한 정보 노출을 방지하고, 잠재적인 보안 취약점을 조기에 발견할 수 있습니다.

활용 방안:

비밀 스캔 활성화: 코드에 민감한 정보가 포함되지 않도록 비밀 스캔 기능을 활용하여 자동으로 감지하고 알림을 받을 수 있습니다.
코드 스캔 통합: 코드 품질과 보안을 유지하기 위해 코드 스캔 도구를 CI 파이프라인에 통합하여 정기적인 검사를 수행합니다.

## 3. 프로젝트 관리 기능 개선
새로운 버전에서는 프로젝트 관리 도구의 사용자 경험이 향상되었습니다. 예를 들어, 이슈 및 풀 리퀘스트의 필터링과 검색 기능이 개선되어 팀의 작업 흐름을 더욱 효율적으로 관리할 수 있습니다.

활용 방안:

이슈 및 PR 관리 효율화: 개선된 필터링과 검색 기능을 활용하여 특정 조건의 이슈나 PR을 신속하게 찾아내고 관리할 수 있습니다.
커스터마이징된 워크플로우 구축: 팀의 요구에 맞게 프로젝트 보드와 워크플로우를 설정하여 작업 진행 상황을 시각적으로 추적하고 조율합니다.

## 4. 성능 및 안정성 향상
3.14.4 버전에서는 전체적인 성능과 안정성이 향상되어, 대규모 팀에서도 원활한 협업이 가능합니다.

활용 방안:

대규모 리포지토리 관리: 성능 향상을 통해 대규모 리포지토리에서도 빠르고 안정적인 작업이 가능합니다.
지속적인 통합 및 배포(CI/CD): 개선된 안정성을 바탕으로 CI/CD 파이프라인의 신뢰성을 높일 수 있습니다.
